"""empty message

Revision ID: 747e3b49868b
Revises: 
Create Date: 2020-02-12 14:32:34.035754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747e3b49868b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('zipcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('state', sa.String(length=15), nullable=True),
    sa.Column('longitude', sa.String(length=25), nullable=True),
    sa.Column('latitude', sa.String(length=25), nullable=True),
    sa.Column('population', sa.String(length=15), nullable=True),
    sa.Column('zip_code', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zipcode')
    op.drop_table('person')
    # ### end Alembic commands ###
